clean: true
objc: true
umbrella_header: LiquidCore/LiquidCore.h
framework_root: .
sdk: iphonesimulator
module: LiquidCore
module_version: 0.7.0
author: LiquidPlayer
author_url: https://github.com/LiquidPlayer
github_url: https://github.com/LiquidPlayer/LiquidCore
copyright: © 2018-2020 LiquidPlayer
hide_documentation_coverage: true
output: ../../../../LiquidPlayer.github.io/LiquidCoreiOS/0.7.0
root_url: https://liquidplayer.github.io/LiquidCoreiOS/0.7.0